"""
Retail Sales & Inventory Intelligence Dashboard
------------------------------------------------
KPIs, filters, trend charts, forecasting and anomaly detection
on top of a SQLite database (retail.db) generated by generate_data.py.

Run with:
    streamlit run app.py
"""

import sqlite3
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from statsmodels.tsa.holtwinters import ExponentialSmoothing

st.set_page_config(page_title="Retail Sales & Inventory Dashboard", layout="wide", page_icon="📊")

# ---------------------------------------------------------
# Global styling — font, heading sizes, blue/black theme
# (color palette itself lives in .streamlit/config.toml)
# ---------------------------------------------------------
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

html, body, [class*="css"] {
    font-family: 'Inter', -apple-system, sans-serif;
}
h1 {
    font-size: 2.1rem !important;
    font-weight: 700 !important;
    letter-spacing: -0.01em;
}
h2 {
    font-size: 1.35rem !important;
    font-weight: 600 !important;
}
h3 {
    font-size: 1.1rem !important;
    font-weight: 600 !important;
}
section[data-testid="stSidebar"] h2 {
    font-size: 1.1rem !important;
}
[data-testid="stMetricLabel"] {
    font-size: 0.85rem !important;
}
[data-testid="stMetricValue"] {
    font-size: 1.5rem !important;
}

/* Round tick-box styling for the sidebar filter checkboxes */
section[data-testid="stSidebar"] [data-testid="stCheckbox"] input[type="checkbox"] {
    appearance: none;
    -webkit-appearance: none;
    width: 18px;
    height: 18px;
    border-radius: 50%;
    border: 2px solid #3b82f6;
    background-color: transparent;
    cursor: pointer;
    position: relative;
}
section[data-testid="stSidebar"] [data-testid="stCheckbox"] input[type="checkbox"]:checked {
    background-color: #3b82f6;
}
section[data-testid="stSidebar"] [data-testid="stCheckbox"] input[type="checkbox"]:checked::after {
    content: "";
    position: absolute;
    left: 5px;
    top: 1px;
    width: 4px;
    height: 8px;
    border: solid white;
    border-width: 0 2px 2px 0;
    transform: rotate(45deg);
}
section[data-testid="stSidebar"] [data-testid="stCheckbox"] label p {
    font-size: 0.9rem !important;
}

/* --- Mobile responsiveness --- */
@media (max-width: 640px) {
    h1 {
        font-size: 1.5rem !important;
    }
    h2 {
        font-size: 1.1rem !important;
    }
    h3 {
        font-size: 0.98rem !important;
    }
    p, .stCaption, [data-testid="stCaptionContainer"] {
        font-size: 0.85rem !important;
    }
    [data-testid="stMetricValue"] {
        font-size: 1.1rem !important;
    }
    [data-testid="stMetricLabel"] {
        font-size: 0.72rem !important;
    }
    /* stack any multi-column row (KPIs, chart pairs, sidebar filter grid)
       into a single column so nothing gets squeezed on a small screen */
    [data-testid="stHorizontalBlock"] {
        flex-direction: column !important;
    }
    [data-testid="stHorizontalBlock"] > div {
        width: 100% !important;
    }
}
</style>
""", unsafe_allow_html=True)

CHART_FONT = dict(family="Inter, sans-serif", size=13, color="#e7ebf3")


def style_fig(fig):
    """Apply a consistent font, size, and blue/black background to every chart."""
    fig.update_layout(
        font=CHART_FONT,
        title_font=dict(family="Inter, sans-serif", size=16, color="#e7ebf3"),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        legend=dict(font=dict(size=12)),
        margin=dict(t=60, b=40, l=40, r=20),
    )
    fig.update_xaxes(title_font=dict(size=13), tickfont=dict(size=11), gridcolor="rgba(148,163,184,0.15)")
    fig.update_yaxes(title_font=dict(size=13), tickfont=dict(size=11), gridcolor="rgba(148,163,184,0.15)")
    return fig

# ---------------------------------------------------------
# Data loading
# ---------------------------------------------------------
@st.cache_data
def load_data():
    conn = sqlite3.connect("retail.db")
    sales = pd.read_sql("SELECT * FROM fact_sales", conn)
    inventory = pd.read_sql("SELECT * FROM dim_inventory", conn)
    conn.close()
    sales["order_date"] = pd.to_datetime(sales["order_date"])
    return sales, inventory

sales, inventory = load_data()

# ---------------------------------------------------------
# Sidebar filters
# ---------------------------------------------------------
st.sidebar.header("Filters")

min_date, max_date = sales["order_date"].min(), sales["order_date"].max()
date_range = st.sidebar.date_input(
    "Date range", value=(min_date, max_date), min_value=min_date, max_value=max_date
)
if len(date_range) == 2:
    start_date, end_date = pd.to_datetime(date_range[0]), pd.to_datetime(date_range[1])
else:
    start_date, end_date = min_date, max_date

st.sidebar.markdown("**Region**")
region_options = sorted(sales["region"].unique())
region_cols = st.sidebar.columns(2)
regions = []
for i, r in enumerate(region_options):
    with region_cols[i % 2]:
        if st.checkbox(r, value=True, key=f"region_{r}"):
            regions.append(r)

st.sidebar.markdown("**Category**")
category_options = sorted(sales["category"].unique())
category_cols = st.sidebar.columns(2)
categories = []
for i, c in enumerate(category_options):
    with category_cols[i % 2]:
        if st.checkbox(c, value=True, key=f"category_{c}"):
            categories.append(c)

if not regions:
    st.sidebar.warning("Select at least one region — showing all regions for now.")
    regions = region_options
if not categories:
    st.sidebar.warning("Select at least one category — showing all categories for now.")
    categories = category_options

filtered = sales[
    (sales["order_date"] >= start_date)
    & (sales["order_date"] <= end_date)
    & (sales["region"].isin(regions))
    & (sales["category"].isin(categories))
]

st.sidebar.caption(f"{len(filtered):,} orders match current filters")

# ---------------------------------------------------------
# Header
# ---------------------------------------------------------
st.title("Retail Sales & Inventory Intelligence Dashboard")
st.caption("A personal data analytics project exploring retail KPIs, seasonal trends, revenue forecasting and inventory risk — built end-to-end in Python.")

st.markdown(
    "In this analysis, I looked at two years of retail transactions across five regions and 25 products. "
    "I tracked revenue and profit trends, flagged unusual sales days, forecasted near-term revenue with "
    "exponential smoothing, and identified which products are at risk of running out of stock."
)

# ---------------------------------------------------------
# KPI row
# ---------------------------------------------------------
total_revenue = filtered["revenue"].sum()
total_profit = filtered["profit"].sum()
margin = (total_profit / total_revenue * 100) if total_revenue else 0
aov = filtered["revenue"].sum() / filtered["order_id"].nunique() if filtered["order_id"].nunique() else 0
units_sold = filtered["quantity"].sum()

# period-over-period comparison (previous period of same length)
period_len = (end_date - start_date).days + 1
prev_start = start_date - pd.Timedelta(days=period_len)
prev_end = start_date - pd.Timedelta(days=1)
prev = sales[
    (sales["order_date"] >= prev_start)
    & (sales["order_date"] <= prev_end)
    & (sales["region"].isin(regions))
    & (sales["category"].isin(categories))
]
prev_revenue = prev["revenue"].sum()
rev_delta = ((total_revenue - prev_revenue) / prev_revenue * 100) if prev_revenue else 0

kpi_cols = st.columns(5)
kpi_cols[0].metric("Total Revenue", f"${total_revenue:,.0f}", f"{rev_delta:+.1f}% vs prior period")
kpi_cols[1].metric("Total Profit", f"${total_profit:,.0f}")
kpi_cols[2].metric("Profit Margin", f"{margin:.1f}%")
kpi_cols[3].metric("Avg Order Value", f"${aov:,.2f}")
kpi_cols[4].metric("Units Sold", f"{units_sold:,}")

st.markdown("---")

# ---------------------------------------------------------
# Tabs
# ---------------------------------------------------------
tab_trends, tab_breakdown, tab_forecast, tab_inventory = st.tabs(
    ["Trends", "Breakdown", "Forecasting", "Inventory"]
)

# --- TRENDS TAB ---
with tab_trends:
    st.subheader("Revenue & Profit Trend")
    st.caption("Aggregated by week to keep the trend easy to read at a glance.")

    daily = filtered.groupby("order_date").agg(revenue=("revenue", "sum"), profit=("profit", "sum")).reset_index()
    weekly = daily.set_index("order_date").resample("W").sum().reset_index()

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=weekly["order_date"], y=weekly["revenue"], name="Revenue",
        line=dict(color="#3b82f6", width=3), fill="tozeroy", fillcolor="rgba(59,130,246,0.12)"
    ))
    fig.add_trace(go.Scatter(
        x=weekly["order_date"], y=weekly["profit"], name="Profit",
        line=dict(color="#93c5fd", width=2, dash="dot")
    ))
    fig.update_layout(
        title="Weekly Revenue & Profit",
        height=380,
        hovermode="x unified",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    fig.update_yaxes(title_text="Amount ($)")
    fig.update_xaxes(title_text="")
    st.plotly_chart(style_fig(fig), use_container_width=True)

    # --- Anomaly detection on monthly revenue (z-score method) ---
    st.subheader("Anomaly Detection")
    st.caption("Monthly revenue with the normal range shaded — months outside the band are flagged as unusual.")

    monthly = daily.set_index("order_date").resample("MS").sum().reset_index()
    monthly["z_score"] = (monthly["revenue"] - monthly["revenue"].mean()) / monthly["revenue"].std()
    anomalies = monthly[np.abs(monthly["z_score"]) > 1.5]

    mean_rev = monthly["revenue"].mean()
    std_rev = monthly["revenue"].std()
    upper_bound = mean_rev + 1.5 * std_rev
    lower_bound = max(mean_rev - 1.5 * std_rev, 0)

    fig_anom = go.Figure()
    fig_anom.add_trace(go.Scatter(
        x=monthly["order_date"], y=[upper_bound] * len(monthly), mode="lines",
        line=dict(width=0), showlegend=False, hoverinfo="skip"
    ))
    fig_anom.add_trace(go.Scatter(
        x=monthly["order_date"], y=[lower_bound] * len(monthly), mode="lines",
        line=dict(width=0), fill="tonexty", fillcolor="rgba(59,130,246,0.08)",
        name="Normal range", hoverinfo="skip"
    ))
    fig_anom.add_trace(go.Scatter(
        x=monthly["order_date"], y=monthly["revenue"], mode="lines+markers", name="Monthly revenue",
        line=dict(color="#3b82f6", width=2.5), marker=dict(size=6)
    ))
    fig_anom.add_trace(go.Scatter(
        x=anomalies["order_date"], y=anomalies["revenue"], mode="markers", name="Flagged anomaly",
        marker=dict(color="#ef4444", size=13, symbol="circle", line=dict(color="white", width=1))
    ))
    fig_anom.update_layout(
        title="Monthly Revenue — Normal Range vs Flagged Anomalies",
        height=380,
        hovermode="x unified",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    fig_anom.update_yaxes(title_text="Revenue ($)")
    fig_anom.update_xaxes(title_text="")
    st.plotly_chart(style_fig(fig_anom), use_container_width=True)

    if len(anomalies):
        st.dataframe(
            anomalies[["order_date", "revenue", "z_score"]]
            .assign(order_date=lambda d: d["order_date"].dt.strftime("%B %Y"))
            .sort_values("order_date", ascending=False),
            use_container_width=True, hide_index=True
        )
    else:
        st.info("No significant anomalies detected in the selected range.")

# --- BREAKDOWN TAB ---
with tab_breakdown:
    c1, c2 = st.columns(2)

    with c1:
        cat_rev = filtered.groupby("category")["revenue"].sum().reset_index().sort_values("revenue", ascending=False)
        fig_cat = px.treemap(cat_rev, path=["category"], values="revenue", title="Revenue by Category",
                              color="revenue", color_continuous_scale="Blues")
        st.plotly_chart(style_fig(fig_cat), use_container_width=True)

    with c2:
        region_rev = filtered.groupby("region")["revenue"].sum().reset_index()
        fig_region = px.bar(region_rev.sort_values("revenue"), x="revenue", y="region", orientation="h",
                             title="Revenue by Region", color="revenue", color_continuous_scale="Blues")
        st.plotly_chart(style_fig(fig_region), use_container_width=True)

    top_products = (
        filtered.groupby("product_name")
        .agg(revenue=("revenue", "sum"), units=("quantity", "sum"))
        .reset_index()
        .sort_values("revenue", ascending=False)
        .head(10)
    )
    st.subheader("Top 10 Products by Revenue")
    fig_top = px.bar(top_products, x="revenue", y="product_name", orientation="h", color="units",
                      color_continuous_scale="Blues")
    fig_top.update_layout(yaxis={"categoryorder": "total ascending"})
    st.plotly_chart(style_fig(fig_top), use_container_width=True)

# --- FORECASTING TAB ---
with tab_forecast:
    st.subheader("Revenue Forecast (Holt-Winters Exponential Smoothing)")
    horizon = st.slider("Forecast horizon (days)", 7, 90, 30)

    ts = sales.groupby("order_date")["revenue"].sum().asfreq("D").fillna(0)

    try:
        model = ExponentialSmoothing(ts, trend="add", seasonal="add", seasonal_periods=7)
        fit = model.fit()
        forecast = fit.forecast(horizon)

        fig_fc = go.Figure()
        fig_fc.add_trace(go.Scatter(x=ts.index[-180:], y=ts.values[-180:], name="Historical", line=dict(color="#2f6fed")))
        fig_fc.add_trace(go.Scatter(x=forecast.index, y=forecast.values, name="Forecast", line=dict(color="#7dd3fc", dash="dash")))
        fig_fc.update_layout(title=f"Next {horizon}-Day Revenue Forecast", height=450, hovermode="x unified")
        st.plotly_chart(style_fig(fig_fc), use_container_width=True)

        fc_total = forecast.sum()
        st.metric(f"Projected revenue — next {horizon} days", f"${fc_total:,.0f}")
    except Exception as e:
        st.warning(f"Forecast could not be generated with current data: {e}")

# --- INVENTORY TAB ---
with tab_inventory:
    st.subheader("Inventory Risk")
    at_risk = inventory[inventory["stockout_flag"] == 1].sort_values("stock_on_hand")
    c1, c2, c3 = st.columns(3)
    c1.metric("Total SKUs", len(inventory))
    c2.metric("At Risk of Stockout", len(at_risk))
    c3.metric("Stockout Rate", f"{len(at_risk) / len(inventory) * 100:.1f}%")

    fig_inv = px.bar(
        inventory.sort_values("stock_on_hand"), x="stock_on_hand", y="product_name",
        orientation="h", color="stockout_flag", color_continuous_scale=["#22c55e", "#ef4444"],
        title="Stock on Hand by Product (red = below reorder level)"
    )
    st.plotly_chart(style_fig(fig_inv), use_container_width=True)

    st.markdown("**Products needing reorder now:**")
    st.dataframe(at_risk[["product_name", "category", "stock_on_hand", "reorder_level"]],
                 use_container_width=True, hide_index=True)

st.markdown("---")
st.caption("Built by Jisna Raj P P — Data Analyst & QA Engineer. Data used here is synthetic and generated for demonstration purposes. Forecasting model: Holt-Winters exponential smoothing.")
